jobfaironline/jobfair-backend

src/main/java/org/capstone/job_fair/config/SecurityConfig.java, src/main/java/org/capstone/job_fair/constants/AccountConstant.java, src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/RegexPattern.java, src/main/java/org/capstone/job_fair/controllers/AccountController.java, src/main/java/org/capstone/job_fair/controllers/AuthController.java, src/main/java/org/capstone/job_fair/jwt/JwtTokenProvider.java, src/main/java/org/capstone/job_fair/jwt/details/UserDetailsServiceImpl.java, src/main/java/org/capstone/job_fair/models/Account.java, src/main/java/org/capstone/job_fair/payload/LoginRequest.java, src/main/java/org/capstone/job_fair/payload/LoginResponse.java, src/main/java/org/capstone/job_fair/payload/RefreshTokenRequest.java, src/main/java/org/capstone/job_fair/payload/RefreshTokenResponse.java, src/main/java/org/capstone/job_fair/repositories/AccountRepository.java, src/main/java/org/capstone/job_fair/services/AccountService.java, src/main/java/org/capstone/job_fair/services/impl/AccountServiceImpl.java, src/main/java/org/capstone/job_fair/validators/impl/EmailValidator.java, src/main/java/org/capstone/job_fair/validators/impl/PasswordValidator.java, src/main/resources/application.properties
=> Cap 16 Implement refresh token

src/main/java/org/capstone/job_fair/config/SecurityConfig.java, src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/access_control/AuthController.java, src/main/java/org/capstone/job_fair/controllers/account/AccountController.java, src/main/java/org/capstone/job_fair/controllers/attendant/AttendantController.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyEmployeeController.java, src/main/java/org/capstone/job_fair/models/dtos/token/AccountVerifyTokenDTO.java, src/main/java/org/capstone/job_fair/models/entities/token/AccountVerifyTokenEntity.java, src/main/java/org/capstone/job_fair/repositories/token/AccountVerifyTokenEntityRepository.java, src/main/java/org/capstone/job_fair/repositories/token/PasswordResetTokenRepository.java, src/main/java/org/capstone/job_fair/services/impl/account/AccountServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/attendant/AttendantServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyEmployeeServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/token/AccountVerifyTokenServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/account/AccountService.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyEmployeeService.java, src/main/java/org/capstone/job_fair/services/interfaces/token/AccountVerifyTokenService.java, src/main/java/org/capstone/job_fair/services/mappers/AccountVerifyTokenMapper.java, src/main/java/org/capstone/job_fair/services/mappers/AttendantMapper.java, src/main/resources/application.properties, src/main/resources/messages.properties
=> [CAP-61] Implement verify account by email for attendant and company manager

src/main/java/org/capstone/job_fair/controllers/access_control/AuthController.java, src/main/java/org/capstone/job_fair/controllers/payload/responses/LoginResponse.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyBenefitMapper.java
=> [CAP-103] Implement Company Manager and Company Employee login return companyId

.github/workflows/ci.yml, src/main/java/org/capstone/job_fair/config/jwt/details/UserDetailsImpl.java, src/main/java/org/capstone/job_fair/config/jwt/details/UserDetailsServiceImpl.java, src/main/java/org/capstone/job_fair/constants/DataConstraint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyController.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/controllers/company/JobController.java, src/main/java/org/capstone/job_fair/controllers/exception/ExceptionHandlerController.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/company/DraftCompanyJobFairRegistrationRequest.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/company/UpdateCompanyRequest.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/job_fair/CancelJobFairRequest.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/job_fair/DraftJobFairPlanRequest.java, src/main/java/org/capstone/job_fair/models/dtos/company/CompanyRegistrationDTO.java, src/main/java/org/capstone/job_fair/models/dtos/job_fair/JobFairDTO.java, src/main/java/org/capstone/job_fair/models/entities/company/CompanyRegistrationEntity.java, src/main/java/org/capstone/job_fair/models/entities/job_fair/JobFairEntity.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyBenefitMapper.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyRegistrationMapper.java, src/main/java/org/capstone/job_fair/services/mappers/company/JobPositionMapper.java, src/main/java/org/capstone/job_fair/services/mappers/company/RegistrationJobPositionMapper.java, src/main/resources/messages.properties
Create Job, not yet check same company
Draft Job fair cannot be create in the past
Draft job fair do not need validation, only when submit to evaluate
Add cancel reason for job fair
Draft company registration do not need validation
Update company profile do not check for matching company
Update company need id as a PathVariable
=> [BE] - Fix minor bug

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java
=> [CAP-164] Implement get all company registration for a job fair ID

src/main/java/org/capstone/job_fair/constants/DataConstraint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/company/UpdateCompanyRequest.java, src/main/resources/messages.properties
[CAP-141] [BE] Successful status logic when restore deleted Job Fair Plan
[CAP-131] [BE] Conflict check valid taxId Logic
[CAP-141]: https://jobfair-capstone.atlassian.net/browse/CAP-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CAP-131]: https://jobfair-capstone.atlassian.net/browse/CAP-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HOT-FIX] 

src/main/java/org/capstone/job_fair/controllers/company/JobController.java, src/main/java/org/capstone/job_fair/repositories/company/job/JobPositionRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/JobPositionServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/JobPositionService.java
=> [CAP-167] implement get all job positions based on company ID

src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/job_fair/UpdateJobFairPlanDraftRequest.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java, src/main/java/org/capstone/job_fair/services/mappers/job_fair/JobFairMapper.java, src/main/resources/messages.properties
=> [CAP-112] Implement update draft job fair

src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyEmployeeController.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyEmployeeRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyEmployeeServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyEmployeeService.java, src/main/java/org/capstone/job_fair/services/mappers/attendant/AttendantMapper.java, src/main/resources/messages.properties
=> [CAP-156] Implement get employee by ID endpoint

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/JobFairConstant.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/repositories/job_fair/JobFairRepository.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java, src/main/resources/messages.properties
=> [CAP-175] Implement get available jobfair for registration based on companyId

src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java
=> [CAP-179] Create draft company registration should return company registration DTO

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyBuyBoothController.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/controllers/job_fair/LayoutController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/company/CompanyBuyBoothRequest.java, src/main/java/org/capstone/job_fair/models/dtos/company/CompanyBoothDTO.java, src/main/java/org/capstone/job_fair/models/entities/company/CompanyBoothEntity.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyBoothRepository.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/repositories/company/OrderRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyBoothPurchaseServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/company/OrderServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/LayoutServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyBoothPurchaseService.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java, src/main/java/org/capstone/job_fair/services/interfaces/company/OrderService.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/LayoutService.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyBoothMapper.java, src/main/java/org/capstone/job_fair/services/mappers/company/OrderMapper.java, src/main/resources/messages.properties
=> [CAP-174] Implement allow company choose booth

src/main/java/org/capstone/job_fair/constants/DataConstraint.java, src/main/java/org/capstone/job_fair/constants/JobPositionConstant.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/JobController.java, src/main/java/org/capstone/job_fair/repositories/company/job/JobPositionRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/JobPositionServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/JobPositionService.java, src/main/resources/messages.properties
=> [CAP-207] Paging get own job position for company

src/main/java/org/capstone/job_fair/constants/AWSConstant.java, src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyBoothLayoutController.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/controllers/payload/responses/RenderJobFairParkResponse.java, src/main/java/org/capstone/job_fair/models/dtos/company/CompanyBoothLayoutDTO.java, src/main/java/org/capstone/job_fair/models/dtos/company/CompanyBoothLayoutVideoDTO.java, src/main/java/org/capstone/job_fair/models/entities/company/CompanyBoothLayoutVideoEntity.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyBoothLayoutVideoRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyBoothLayoutServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyBoothLayoutService.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyBoothLayoutMapper.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyBoothLayoutVideoMapper.java
=> [CAP-180] allow video for 3D map

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/models/dtos/job_fair/AttendantJobFairStatusDTO.java, src/main/java/org/capstone/job_fair/models/entities/job_fair/AttendantJobFairStatusEntity.java, src/main/java/org/capstone/job_fair/models/statuses/JobFairAttendantStatus.java, src/main/java/org/capstone/job_fair/repositories/job_fair/AttendantJobFairStatusRepository.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java, src/main/java/org/capstone/job_fair/services/mappers/job_fair/AttendantJobFairStatusMapper.java, src/main/resources/application.properties
=> [CAP-218] - revamp job fair status for attendant

src/main/java/org/capstone/job_fair/constants/DataConstraint.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/job_fair/DraftJobFairPlanRequest.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/job_fair/UpdateJobFairPlanDraftRequest.java, src/main/java/org/capstone/job_fair/models/dtos/job_fair/JobFairDTO.java, src/main/java/org/capstone/job_fair/models/entities/job_fair/JobFairEntity.java
=> [CAP-216] add more fields for job fair

src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/repositories/job_fair/JobFairRepository.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java
=> [CAP-220]  Implement get job fairs registration based on creator

pom.xml, src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/CSVConstant.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/JobController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/company/CreateJobPositionRequest.java, src/main/java/org/capstone/job_fair/models/dtos/company/job/JobPositionDTO.java, src/main/java/org/capstone/job_fair/services/impl/company/JobPositionServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/JobPositionService.java, src/main/java/org/capstone/job_fair/utils/OpenCSV/ListConverter.java, src/main/resources/messages.properties
=> [CAP-217] Implement import excel file with job positions

src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/repositories/job_fair/AdminJobFairStatusRepository.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java
=> [CAP-229] Fix API: Allow to filter more than 1 status

src/main/java/org/capstone/job_fair/constants/JobPositionConstant.java, src/main/java/org/capstone/job_fair/models/dtos/company/job/JobPositionDTO.java, src/main/java/org/capstone/job_fair/models/entities/company/job/JobPositionEntity.java, src/main/java/org/capstone/job_fair/services/impl/company/JobPositionServiceImpl.java
=> [CAP-232] Add created date into Job Position

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/models/dtos/company/CompanyRegistrationDTO.java, src/main/java/org/capstone/job_fair/models/entities/company/CompanyRegistrationEntity.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java, src/main/resources/messages.properties
=> [CAP-241] Implement draft API

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java
=> [CAP-243] Implement API for get history of job fair that company registered or attendant joined

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/controllers/payload/responses/CompanyRegistrationResponse.java, src/main/java/org/capstone/job_fair/models/dtos/company/CompanyRegistrationAdminDTO.java, src/main/java/org/capstone/job_fair/models/entities/company/CompanyRegistrationAdminEntity.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationAdminRepository.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRepository.java, src/main/java/org/capstone/job_fair/repositories/job_fair/JobFairRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java, src/main/java/org/capstone/job_fair/services/mappers/company/CompanyRegistrationMapper.java, src/main/resources/application.properties, src/main/resources/messages.properties
Add company name in response
get all api
search company registration by company name and job fair name
=> [CAP-239] Refactor company registrations for admin API

src/main/java/org/capstone/job_fair/controllers/company/CompanyRegistrationController.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/CompanyRegistrationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/CompanyRegistrationService.java
=> [CAP-231] Implements get all company registrations

src/main/java/org/capstone/job_fair/constants/JobFairConstant.java, src/main/java/org/capstone/job_fair/controllers/company/JobController.java, src/main/java/org/capstone/job_fair/controllers/job_fair/JobFairController.java, src/main/java/org/capstone/job_fair/repositories/company/CompanyRegistrationRepository.java, src/main/java/org/capstone/job_fair/repositories/company/job/JobPositionRepository.java, src/main/java/org/capstone/job_fair/repositories/job_fair/AdminJobFairStatusRepository.java, src/main/java/org/capstone/job_fair/repositories/job_fair/AttendantJobFairStatusRepository.java, src/main/java/org/capstone/job_fair/repositories/job_fair/CompanyJobFairStatusRepository.java, src/main/java/org/capstone/job_fair/repositories/job_fair/JobFairRepository.java, src/main/java/org/capstone/job_fair/services/impl/company/JobPositionServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/job_fair/JobFairServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/company/JobPositionService.java, src/main/java/org/capstone/job_fair/services/interfaces/job_fair/JobFairService.java, src/main/java/org/capstone/job_fair/validators/XSSConstraint.java
Search job fair in job fair list for attendant 
Search job fair in get job fair list cho manager 
Search position in job position list
Search job fair in job fair list for admin 
Search job fair in job fair plan list for admin
=> [CAP-267]  Implement search for various api

src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/attendant/cv/ApplicationController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/account/cv/CreateApplicationRequest.java, src/main/java/org/capstone/job_fair/repositories/attendant/cv/CvRepository.java, src/main/java/org/capstone/job_fair/services/impl/attendant/cv/ApplicationServiceImpl.java, src/main/java/org/capstone/job_fair/services/impl/attendant/cv/CvServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/attendant/cv/CvService.java, src/main/java/org/capstone/job_fair/services/mappers/attendant/cv/ApplicationMapper.java, src/main/java/org/capstone/job_fair/services/mappers/attendant/cv/CvMapper.java, src/main/java/org/capstone/job_fair/services/mappers/company/RegistrationJobPositionMapper.java, src/main/resources/messages.properties
=> [CAP-292] Update create application api with new flow

src/main/java/org/capstone/job_fair/constants/ApiEndPoint.java, src/main/java/org/capstone/job_fair/constants/DataConstraint.java, src/main/java/org/capstone/job_fair/constants/MessageConstant.java, src/main/java/org/capstone/job_fair/controllers/attendant/cv/ApplicationController.java, src/main/java/org/capstone/job_fair/controllers/payload/requests/attendant/cv/EvaluateApplicationRequest.java, src/main/java/org/capstone/job_fair/models/dtos/attendant/cv/ApplicationDTO.java, src/main/java/org/capstone/job_fair/models/entities/attendant/cv/ApplicationEntity.java, src/main/java/org/capstone/job_fair/repositories/attendant/cv/ApplicationRepository.java, src/main/java/org/capstone/job_fair/services/impl/attendant/cv/ApplicationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/attendant/ApplicationService.java, src/main/java/org/capstone/job_fair/services/mappers/attendant/cv/ApplicationMapper.java, src/main/resources/messages.properties
=> [CAP-284] Implement evaluate application

src/main/java/org/capstone/job_fair/constants/ApplicationConstant.java, src/main/java/org/capstone/job_fair/controllers/attendant/cv/ApplicationController.java, src/main/java/org/capstone/job_fair/controllers/payload/responses/ApplicationForAttendantResponse.java, src/main/java/org/capstone/job_fair/repositories/attendant/cv/ApplicationRepository.java, src/main/java/org/capstone/job_fair/services/impl/attendant/cv/ApplicationServiceImpl.java, src/main/java/org/capstone/job_fair/services/interfaces/attendant/ApplicationService.java, src/main/java/org/capstone/job_fair/services/mappers/attendant/cv/ApplicationMapper.java
=> [CAP-295] implement get all application as an attendant
